// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.ts
// For now, we define the basic structure manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type RecipeVisibility = 'private' | 'friends' | 'followers' | 'public';
export type FriendshipStatus = 'pending' | 'accepted';
export type NotificationType =
  | 'friend_request'
  | 'friend_accepted'
  | 'recipe_shared'
  | 'list_shared'
  | 'new_follower';
export type DayOfWeek =
  | 'sunday'
  | 'monday'
  | 'tuesday'
  | 'wednesday'
  | 'thursday'
  | 'friday'
  | 'saturday';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string;
          avatar_url: string | null;
          bio: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          display_name: string;
          avatar_url?: string | null;
          bio?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          display_name?: string;
          avatar_url?: string | null;
          bio?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_settings: {
        Row: {
          id: string;
          first_day_of_week: DayOfWeek;
          notify_friend_requests: boolean;
          notify_friend_accepted: boolean;
          notify_recipe_shared: boolean;
          notify_list_shared: boolean;
          notify_new_follower: boolean;
          push_notifications_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          first_day_of_week?: DayOfWeek;
          notify_friend_requests?: boolean;
          notify_friend_accepted?: boolean;
          notify_recipe_shared?: boolean;
          notify_list_shared?: boolean;
          notify_new_follower?: boolean;
          push_notifications_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_day_of_week?: DayOfWeek;
          notify_friend_requests?: boolean;
          notify_friend_accepted?: boolean;
          notify_recipe_shared?: boolean;
          notify_list_shared?: boolean;
          notify_new_follower?: boolean;
          push_notifications_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      recipes: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          servings: number | null;
          prep_time_minutes: number | null;
          cook_time_minutes: number | null;
          image_url: string | null;
          source_url: string | null;
          visibility: RecipeVisibility;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          servings?: number | null;
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          image_url?: string | null;
          source_url?: string | null;
          visibility?: RecipeVisibility;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          servings?: number | null;
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          image_url?: string | null;
          source_url?: string | null;
          visibility?: RecipeVisibility;
          created_at?: string;
          updated_at?: string;
        };
      };
      ingredients: {
        Row: {
          id: string;
          recipe_id: string;
          name: string;
          quantity: number | null;
          quantity_display: string | null;
          unit: string | null;
          notes: string | null;
          position: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          name: string;
          quantity?: number | null;
          quantity_display?: string | null;
          unit?: string | null;
          notes?: string | null;
          position: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          name?: string;
          quantity?: number | null;
          quantity_display?: string | null;
          unit?: string | null;
          notes?: string | null;
          position?: number;
          created_at?: string;
        };
      };
      instructions: {
        Row: {
          id: string;
          recipe_id: string;
          step_number: number;
          instruction: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          step_number: number;
          instruction: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          step_number?: number;
          instruction?: string;
          created_at?: string;
        };
      };
      follows: {
        Row: {
          id: string;
          follower_id: string;
          following_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          follower_id: string;
          following_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          follower_id?: string;
          following_id?: string;
          created_at?: string;
        };
      };
      friendships: {
        Row: {
          id: string;
          user_id: string;
          friend_id: string;
          status: FriendshipStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          friend_id: string;
          status?: FriendshipStatus;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          friend_id?: string;
          status?: FriendshipStatus;
          created_at?: string;
          updated_at?: string;
        };
      };
      shared_recipes: {
        Row: {
          id: string;
          recipe_id: string;
          shared_by: string;
          shared_with: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          shared_by: string;
          shared_with: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          shared_by?: string;
          shared_with?: string;
          created_at?: string;
        };
      };
      meal_plan_entries: {
        Row: {
          id: string;
          user_id: string;
          recipe_id: string | null;
          date: string;
          meal_label: string | null;
          servings: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          recipe_id?: string | null;
          date: string;
          meal_label?: string | null;
          servings?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          recipe_id?: string | null;
          date?: string;
          meal_label?: string | null;
          servings?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      grocery_lists: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      grocery_list_collaborators: {
        Row: {
          list_id: string;
          user_id: string;
          can_edit: boolean;
          created_at: string;
        };
        Insert: {
          list_id: string;
          user_id: string;
          can_edit?: boolean;
          created_at?: string;
        };
        Update: {
          list_id?: string;
          user_id?: string;
          can_edit?: boolean;
          created_at?: string;
        };
      };
      grocery_items: {
        Row: {
          id: string;
          list_id: string;
          recipe_id: string | null;
          name: string;
          quantity: number | null;
          quantity_display: string | null;
          unit: string | null;
          checked: boolean;
          added_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          list_id: string;
          recipe_id?: string | null;
          name: string;
          quantity?: number | null;
          quantity_display?: string | null;
          unit?: string | null;
          checked?: boolean;
          added_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          list_id?: string;
          recipe_id?: string | null;
          name?: string;
          quantity?: number | null;
          quantity_display?: string | null;
          unit?: string | null;
          checked?: boolean;
          added_by?: string | null;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: NotificationType;
          data: Json;
          read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: NotificationType;
          data?: Json;
          read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: NotificationType;
          data?: Json;
          read?: boolean;
          created_at?: string;
        };
      };
    };
    Functions: {
      are_friends: {
        Args: { user1: string; user2: string };
        Returns: boolean;
      };
      is_following: {
        Args: { follower: string; followee: string };
        Returns: boolean;
      };
    };
  };
}

// Convenience types
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type UserSettings = Database['public']['Tables']['user_settings']['Row'];
export type Recipe = Database['public']['Tables']['recipes']['Row'];
export type Ingredient = Database['public']['Tables']['ingredients']['Row'];
export type Instruction = Database['public']['Tables']['instructions']['Row'];
export type Follow = Database['public']['Tables']['follows']['Row'];
export type Friendship = Database['public']['Tables']['friendships']['Row'];
export type SharedRecipe = Database['public']['Tables']['shared_recipes']['Row'];
export type MealPlanEntry = Database['public']['Tables']['meal_plan_entries']['Row'];
export type GroceryList = Database['public']['Tables']['grocery_lists']['Row'];
export type GroceryListCollaborator = Database['public']['Tables']['grocery_list_collaborators']['Row'];
export type GroceryItem = Database['public']['Tables']['grocery_items']['Row'];
export type Notification = Database['public']['Tables']['notifications']['Row'];
